# Generated by Django 4.2.1 on 2023-06-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='recommendations',
            field=models.TextField(blank=True),
        ),
    ]
