# Generated by Django 4.2.1 on 2023-06-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_appointment_recommendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='room',
            field=models.IntegerField(default=0),
        ),
    ]
