# Generated by Django 4.2.1 on 2023-06-08 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_patient_allergies_patient_medication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='medication',
            new_name='medications',
        ),
    ]
