# Generated by Django 4.2.1 on 2023-06-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_doctor_working_days_alter_doctor_working_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='room',
            field=models.IntegerField(default=0),
        ),
    ]
