# Generated by Django 4.2.1 on 2023-06-06 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_remove_doctor_working_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('short', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='working_days',
            field=models.ManyToManyField(to='doctor.day'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='working_hours',
            field=models.ManyToManyField(to='doctor.hour'),
        ),
    ]
